name: Pull Request
'on':
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        scala-version: [2.12.15, 2.13.7]
    runs-on: ubuntu-latest
    env:
      ACTION_JDK_VERSION: openjdk8
      SCALA_VERSION: ${{ matrix.scala-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: olafurpg/setup-scala@v11
      with:
        java-version: adopt@1.8.0
    - run: sbt ++$SCALA_VERSION clean coverage test
    - run: sbt ++$SCALA_VERSION coverageReport
    - run: sbt ++$SCALA_VERSION coverageAggregate
